name: Update COVID-19 Data
on:
  #schedule:
  #  - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  update-data:
    name: Update COVID-19 Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Script
        run: python fetch.py
      - name: Commit Changes to Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data Updated
